[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
    name = "pack.ag/amqp"
    branch = "master"

[[constraint]]
    name = "github.com/Azure/azure-sdk-for-go"
    version = "14"

[[constraint]]
    name = "github.com/Azure/azure-amqp-common-go"
    branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  branch = "master"
